name: Bug Report (English)
description: I encounter a bug while playing the game
title: "[Bug] Enter a title for this issue"
labels: ["bug", "user issue", "english"]
assignees:
  - AurelienAudero
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report
  - type: textarea
    id: configuration
    attributes:
      label: What is your configuration ?
      description: Please specify at least the CPU, RAM, OS Version and Python version you are using
      value: |
        - CPU:
        - RAM: 
        - GPU:
        - OS Version:
        - Python Version:
        - Pyxel Version:
        - Pygame Version:
        - Additional infos:
    validations:
      required: true
  - type: textarea
    id: describe-the-bug
    attributes :
      label: Describe the Bug
      description: A clear and concise description of the bug you encountered.
      value: "A bug happened !"
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: How did you produce this bug ?
      value: |
        1. I launched the game using the terminal
        2. I select...
    validations:
      required: true
  - type: textarea
    id: anything-else
    attributes:
      label: Anything else ?
      description: |
        Links ? References ? Anything that will give us more context about the issue you are encountering
        
        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in
  - type: checkboxes
    id: checklist
    attributes:
      label: I'm checking my form
      description: Check through this checklist that the form has been completed correctly.
      options:
        - label: I have specified a title related to my problem
          required: true
        - label: My title starts with "[Bug]" (without the quotes)
          required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/AurelienAudero/KinoDerToten-Pyxel-Game/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
      