name: Bug/Issue Report (French)
description: J'ai rencontré un bug en jouant au jeu
title: "[Bug] Entrer un titre pour cette issue"
labels: ["bug", "user issue", "french"]
assignees:
  - AurelienAudero
body:
  - type: markdown
    attributes:
      value: |
        Merci de prendre le temps pour remplir ce rapport de bug
  - type: textarea
    id: configuration
    attributes:
      label: Quel est votre configuration ?
      description: Veuillez préciser au moins le CPU, la RAM, la version de l'OS et la version de Python que vous utilisez
      value: |
        - CPU :
        - RAM :
        - GPU :
        - Version de l'OS :
        - Version de Python :
        - Version de Pyxel :
        - Version de Pygame :
        - Infos Additionnelles :
    validations:
      required: true
  - type: textarea
    id: decrivez-le-bug
    attributes :
      label: Décrivez le bug
      description: Une description claire et concise du bug que vous avez rencontré.
      value: "Un bug est arrivé !"
    validations:
      required: true
  - type: textarea
    id: etapes-pour-le-reproduire
    attributes:
      label: Étapes pour le reproduire
      description: Comment avez-vous fait ce bug ?
      value: |
        1. Je lance le jeu en utilisant le terminal
        2. Je sélectionne...
    validations:
      required: true
  - type: textarea
    id: autre-chose
    attributes:
      label: Autre chose ?
      description: |
        Liens ? Références ? Tout ce qui nous donnera plus de contexte sur le problème que vous rencontrez
        
        Astuce: Vous pouvez joindre des images ou des fichiers log en cliquant sur cette zone pour la mettre en surbrillance, puis en faisant glisser des fichiers à l'intérieur de celle-ci
  - type: checkboxes
    id: checklist
    attributes:
      label: Je vérifie mon formulaire
      description: Vérifiez grâce à cette checklist que le formulaire est correct et qu'il a été rempli correctement.
      options:
        - label: J'ai bien spécifié un titre en rapport avec mon problème
          required: true
        - label: Mon titre commence par "[Bug]" (sans les guillemets)
          required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code de Conduite
      description: En soumettant ce problème, vous acceptez de suivre notre [Code de Conduite](https://github.com/AurelienAudero/KinoDerToten-Pyxel-Game/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: J'accepte de suivre le code de conduite de ce projet
          required: true
      